"""rename department

Revision ID: feb9e8efa4d3
Revises: 0c144cd8d840
Create Date: 2024-06-28 16:51:32.347779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb9e8efa4d3'
down_revision = '0c144cd8d840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
